name: Nightly update — ArbiSense data

on:
  schedule:
    - cron: '0 0 * * *'   # ogni giorno a 00:00 UTC
  workflow_dispatch: {}   # permette trigger manuale

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run MVP (fetch -> calc -> plot)
        run: |
          python scripts/run_mvp.py

      - name: Export strong signals
        run: |
          python scripts/export_strong_signals.py

      - name: Send Telegram alerts (optional)
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python scripts/send_alerts.py || echo "send_alerts.py exited non-zero or found no signals"

      - name: Commit and push generated data to branch data-updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data_sample/ reports/
          if ! git diff --staged --quiet; then
            git commit -m "chore: nightly update data (auto) — $GITHUB_RUN_ID"
            git push origin HEAD:data-updates
          else
            echo "No new/updated files to commit."
          fi
